export const SHEETS = {
  users: 'users',
  userProfiles: 'user_profiles',
  userRoles: 'user_roles',
  authIdentities: 'auth_identities',
  facilitatorUserAccess: 'facilitator_user_access',
  visitorLeads: 'visitor_leads',
  sessions: 'sessions',
  sessionModules: 'session_modules',
  moduleRuns: 'module_runs',
  moduleRunVersions: 'module_run_versions',
  moduleReports: 'module_reports',
  dashboardSnapshots: 'dashboard_snapshots',
  usageLogs: 'usage_logs',
  exportLogs: 'export_logs',
  integrationJobs: 'integration_jobs',
};

export const SCHEMA = {
  users: ['id', 'email', 'password_hash', 'email_verified_at', 'status', 'created_at', 'updated_at', 'last_login_at'],
  user_profiles: ['id', 'user_id', 'display_name', 'avatar_url', 'phone', 'school_org', 'note', 'created_at', 'updated_at'],
  user_roles: ['id', 'user_id', 'role_code', 'role_start_at', 'role_end_at', 'created_at'],
  auth_identities: ['id', 'user_id', 'provider', 'provider_uid', 'created_at'],
  facilitator_user_access: ['id', 'facilitator_user_id', 'target_user_id', 'source_type', 'source_ref_id', 'created_at'],
  visitor_leads: ['id', 'email', 'source_module_code', 'consent_version', 'consent_at', 'report_token', 'converted_user_id', 'created_at'],
  sessions: ['id', 'user_id', 'visitor_lead_id', 'session_type', 'entry_mode', 'started_at', 'completed_at', 'current_status', 'derived_career_state', 'facilitator_user_id', 'source_channel', 'created_at', 'updated_at'],
  session_modules: ['id', 'session_id', 'module_code', 'sequence_no', 'is_required', 'started_at', 'completed_at', 'status', 'created_at'],
  module_runs: ['id', 'user_id', 'visitor_lead_id', 'session_id', 'module_code', 'run_mode', 'status', 'current_version_no', 'latest_report_id', 'started_at', 'completed_at', 'created_at', 'updated_at'],
  module_run_versions: ['id', 'module_run_id', 'version_no', 'input_payload', 'derived_payload', 'output_payload', 'save_type', 'changed_by_user_id', 'created_at'],
  module_reports: ['id', 'module_run_id', 'report_type', 'report_title', 'report_json', 'report_html', 'report_pdf_url', 'visibility_scope', 'created_at'],
  dashboard_snapshots: ['id', 'user_id', 'source_session_id', 'snapshot_label', 'snapshot_date', 'summary_json', 'scoring_json', 'created_at'],
  usage_logs: ['id', 'actor_type', 'actor_user_id', 'visitor_lead_id', 'action_code', 'module_code', 'ref_id', 'payload', 'created_at'],
  export_logs: ['id', 'user_id', 'report_id', 'export_type', 'status', 'created_at', 'finished_at'],
  integration_jobs: ['id', 'integration_type', 'source_type', 'source_id', 'request_payload', 'response_payload', 'status', 'created_at', 'updated_at'],
};
